
package servcli;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServWebService", targetNamespace = "http://servweb/", wsdlLocation = "http://localhost:9999/ws/mensaje?wsdl")
public class ServWebService
    extends Service
{

    private final static URL SERVWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVWEBSERVICE_EXCEPTION;
    private final static QName SERVWEBSERVICE_QNAME = new QName("http://servweb/", "ServWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/mensaje?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVWEBSERVICE_WSDL_LOCATION = url;
        SERVWEBSERVICE_EXCEPTION = e;
    }

    public ServWebService() {
        super(__getWsdlLocation(), SERVWEBSERVICE_QNAME);
    }

    public ServWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVWEBSERVICE_QNAME, features);
    }

    public ServWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVWEBSERVICE_QNAME);
    }

    public ServWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVWEBSERVICE_QNAME, features);
    }

    public ServWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Mensaje
     */
    @WebEndpoint(name = "ServWebPort")
    public Mensaje getServWebPort() {
        return super.getPort(new QName("http://servweb/", "ServWebPort"), Mensaje.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Mensaje
     */
    @WebEndpoint(name = "ServWebPort")
    public Mensaje getServWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servweb/", "ServWebPort"), Mensaje.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVWEBSERVICE_EXCEPTION!= null) {
            throw SERVWEBSERVICE_EXCEPTION;
        }
        return SERVWEBSERVICE_WSDL_LOCATION;
    }

}
